// ====== Mock data for ADB_Helper prototype ======
const MOCK_DEVICES = [
  {
    serial: "2B161FDH200123",
    model: "Pixel 7 Pro",
    manufacturer: "Google",
    brand: "google",
    codename: "cheetah",
    connection: "usb",
    status: "online",
    ip: "",
    android: "14",
    api: "34",
    abi: "arm64-v8a",
    cpuName: "Google Tensor G2",
    cpuArch: "arm64-v8a",
    cores: 8,
    cpuMax: 2850,
    cpuMin: 300,
    governor: "schedutil",
    gpuVendor: "ARM",
    gpuRenderer: "Mali-G710 MC10",
    gles: "3.2",
    ramTotal: 12288,
    ramAvail: 4112,
    swap: 4096,
    storageTotal: 128000,
    storageAvail: 51200,
    resolution: "1440 × 3120",
    dpi: 512,
    refresh: "120 Hz",
    battery: 87,
    batStatus: "Discharging",
    batHealth: "Good",
    batTemp: 31.5,
    batTech: "Li-ion",
    batVoltage: 4185,
    securityPatch: "2026-03-05",
    buildId: "AP2A.240805.005.S1",
    fingerprint: "google/cheetah/cheetah:14/AP2A.240805.005.S1/12087921:user/release-keys",
    buildType: "user",
    buildDate: "Wed Aug 14 18:23:11 UTC 2025",
    bootloader: "cheetah-1.4-12345678",
    baseband: "g5300n-241101-250131-B-13745432",
    wifiIp: "192.168.1.18",
    wifiMac: "84:0d:8e:1a:bc:42",
    btMac: "84:0d:8e:1a:bc:43",
    imei: "N/A",
    locale: "en-US",
    timezone: "America/Los_Angeles",
  },
  {
    serial: "192.168.1.42:5555",
    model: "Pixel 6a",
    manufacturer: "Google",
    brand: "google",
    codename: "bluejay",
    connection: "wifi",
    status: "online",
    ip: "192.168.1.42",
    android: "14",
    api: "34",
    abi: "arm64-v8a",
    cpuName: "Google Tensor",
    cpuArch: "arm64-v8a",
    cores: 8,
    cpuMax: 2802,
    governor: "schedutil",
    gpuRenderer: "Mali-G78 MP20",
    ramTotal: 6144,
    ramAvail: 2304,
    storageTotal: 128000,
    storageAvail: 71000,
    resolution: "1080 × 2400",
    dpi: 429,
    refresh: "60 Hz",
    battery: 64,
    batStatus: "Charging",
    batHealth: "Good",
    batTemp: 28.2,
  },
  {
    serial: "OP116E2A8F",
    model: "OnePlus 11",
    manufacturer: "OnePlus",
    brand: "OnePlus",
    codename: "salami",
    connection: "usb",
    status: "unauthorized",
    ip: "",
  },
  {
    serial: "192.168.1.108:5555",
    model: "Galaxy Tab S8",
    manufacturer: "Samsung",
    connection: "wifi",
    status: "offline",
    ip: "192.168.1.108",
  },
];

const MOCK_PAIRED = [
  { alias: "Pixel 6a (home)", ip: "192.168.1.42", last: "2 hours ago" },
  { alias: "Galaxy Tab S8", ip: "192.168.1.108", last: "Yesterday" },
  { alias: "Pixel 4 (test)", ip: "192.168.1.55", last: "Mar 9" },
  { alias: "OnePlus 11 (wifi)", ip: "192.168.1.71", last: "Mar 4" },
];

const MOCK_MACROS = [
  { name: "Capture bug logs", cmds: 5, last: "Today" },
  { name: "Reset perms — com.example", cmds: 8, last: "Yesterday" },
  { name: "Doze + idle stats", cmds: 4, last: "Mar 11" },
  { name: "Clear cache — Chrome", cmds: 3, last: "Mar 7" },
  { name: "Set up demo device", cmds: 14, last: "Feb 28" },
];

const MOCK_HISTORY = [
  "dumpsys battery",
  "pm list packages -3",
  "settings get global airplane_mode_on",
  "getprop ro.build.fingerprint",
  "input keyevent KEYCODE_HOME",
  "logcat -d -t 200 *:E",
  "wm density",
  "pm grant com.example.app android.permission.CAMERA",
  "dumpsys deviceidle force-idle",
  "am start -n com.android.settings/.Settings",
];

const MOCK_APPS = [
  { name: "Chrome", pkg: "com.android.chrome", type: "system", status: "active", size: 412 },
  { name: "Photos", pkg: "com.google.android.apps.photos", type: "system", status: "active", size: 318 },
  { name: "YouTube", pkg: "com.google.android.youtube", type: "system", status: "active", size: 287 },
  { name: "Maps", pkg: "com.google.android.apps.maps", type: "system", status: "active", size: 254 },
  { name: "Gmail", pkg: "com.google.android.gm", type: "system", status: "active", size: 201 },
  { name: "Calendar", pkg: "com.google.android.calendar", type: "system", status: "active", size: 95 },
  { name: "Slack", pkg: "com.Slack", type: "user", status: "active", size: 188 },
  { name: "Spotify", pkg: "com.spotify.music", type: "user", status: "active", size: 162 },
  { name: "Notion", pkg: "notion.id", type: "user", status: "active", size: 142 },
  { name: "Discord", pkg: "com.discord", type: "user", status: "active", size: 131 },
  { name: "Telegram", pkg: "org.telegram.messenger", type: "user", status: "active", size: 119 },
  { name: "Signal", pkg: "org.thoughtcrime.securesms", type: "user", status: "active", size: 98 },
  { name: "Figma", pkg: "com.figma.mirror", type: "user", status: "disabled", size: 64 },
  { name: "Bookings", pkg: "com.booking", type: "user", status: "disabled", size: 86 },
  { name: "Lyft", pkg: "me.lyft.android", type: "user", status: "active", size: 102 },
  { name: "Uber", pkg: "com.ubercab", type: "user", status: "active", size: 134 },
  { name: "GitHub", pkg: "com.github.android", type: "user", status: "active", size: 53 },
  { name: "Reddit", pkg: "com.reddit.frontpage", type: "user", status: "active", size: 110 },
  { name: "1Password", pkg: "com.onepassword.android", type: "user", status: "active", size: 87 },
  { name: "VS Code", pkg: "com.code.android", type: "user", status: "active", size: 92 },
  { name: "Calculator", pkg: "com.google.android.calculator", type: "system", status: "active", size: 22 },
  { name: "Clock", pkg: "com.google.android.deskclock", type: "system", status: "active", size: 18 },
  { name: "Files", pkg: "com.google.android.apps.nbu.files", type: "system", status: "active", size: 45 },
  { name: "Drive", pkg: "com.google.android.apps.docs", type: "system", status: "active", size: 178 },
  { name: "Translate", pkg: "com.google.android.apps.translate", type: "system", status: "active", size: 89 },
];

const MOCK_INSTALL_FILES = [
  { name: "app-release-v3.14.2.apk", size: 24.7, type: "apk" },
  { name: "demo-suite.apks", size: 142.3, type: "apks" },
  { name: "test-fixtures.xapk", size: 86.1, type: "xapk" },
];

const MODULES = [
  { id: "connections", label: "Connections", icon: "link" },
  { id: "terminal", label: "Terminal", icon: "terminal" },
  { id: "installer", label: "Installer", icon: "package" },
  { id: "scrcpy", label: "Scrcpy", icon: "cast" },
  { id: "buttons", label: "Device Buttons", icon: "buttons" },
  { id: "info", label: "Device Info", icon: "info" },
  { id: "apps", label: "Apps", icon: "grid" },
  { id: "logcat", label: "Logcat", icon: "logs" },
];

const SECONDARY_MODULES = [
  { id: "settings", label: "Settings", icon: "settings" },
];

Object.assign(window, {
  MOCK_DEVICES, MOCK_PAIRED, MOCK_MACROS, MOCK_HISTORY,
  MOCK_APPS, MOCK_INSTALL_FILES, MODULES, SECONDARY_MODULES,
});
